# Generated by Django 6.0.1 on 2026-02-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('display_name', models.CharField(max_length=32)),
                ('profile_image_url', models.URLField(max_length=256)),
                ('bio_text', models.TextField(max_length=256)),
                ('join_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
