# Generated by Django 6.0.1 on 2026-04-21 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycloset', '0002_rename_friend_friendrequest_friendship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothingitem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='requesting_user',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='responding_user',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='user2',
        ),
        migrations.RemoveField(
            model_name='outfit',
            name='user',
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mycloset.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='requesting_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='mycloset.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='responding_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='mycloset.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friendship',
            name='profile1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='friendship_profile1', to='mycloset.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friendship',
            name='profile2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='friendship_profile2', to='mycloset.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outfit',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mycloset.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='rater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycloset.profile'),
        ),
    ]
