# Generated by Django 6.0.1 on 2026-04-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycloset', '0003_remove_clothingitem_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='accessory_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfit',
            name='accessory_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfit',
            name='accessory_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfit',
            name='accessory_y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfit',
            name='bottom_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfit',
            name='bottom_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfit',
            name='bottom_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfit',
            name='bottom_y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfit',
            name='shoes_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfit',
            name='shoes_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfit',
            name='shoes_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfit',
            name='shoes_y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfit',
            name='top_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfit',
            name='top_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfit',
            name='top_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfit',
            name='top_y',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
